name: 'publish'

on:
  workflow_dispatch:  # allows manual triggering of the workflow

jobs:
  publish:
    permissions:
      contents: write  # necessary to create releases
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            target: 'aarch64-apple-darwin'
          - platform: 'macos-latest'
            target: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            target: 'x86_64-unknown-linux-gnu'
          - platform: 'ubuntu-22.04'
            target: 'aarch64-unknown-linux-gnu'
          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
          - platform: 'windows-latest'
            target: 'aarch64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: build
        run: cargo build --release --target ${{ matrix.target }}
        
      - name: rename file (windows)
        if: matrix.platform == 'windows-latest'
        run: Rename-Item -Path target\\${{ matrix.target }}\\release\\launcher.exe -NewName launcher-${{ matrix.target }}.exe    
      - name: rename file (unix)
        if: matrix.platform != 'windows-latest'
        run: mv target/${{ matrix.target }}/release/launcher target/${{ matrix.target }}/release/launcher-${{ matrix.target }}
      
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/launcher-${{ matrix.target }}${{ matrix.platform == 'windows-latest' && '.exe' || '' }}
          tag_name: "v4"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # automatically provided secret
